server:
  port: 8081 # ì„œë²„ í¬íŠ¸

spring:
  application:
    name: devpath

  # ìŠ¤í”„ë§ì´ ìµœìƒë‹¨ ë£¨íŠ¸ì— ìˆëŠ” .env íŒŒì¼ì„ ê°•ì œë¡œ ì½ì–´ì˜¤ë„ë¡ ì§€ì‹œ
  config:
    import: optional:file:.env[.properties]

  # PostgreSQL ì„¤ì •
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:devpath_db}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # sql ìë™ ì‹¤í–‰ ì˜µì…˜
  sql:
    init:
      mode: always

  # JPA ë° í•˜ì´ë²„ë„¤ì´íŠ¸ ì„¤ì •
  jpa:
     hibernate:
       ddl-auto: create
     show-sql: true
     defer-datasource-initialization: true  # ğŸ”¥ [ì¶”ê°€í•  ë¶€ë¶„] JPA í…Œì´ë¸” ìƒì„± í›„ data.sqlì„ ì‹¤í–‰í•˜ë¼ëŠ” í•µì‹¬ ì˜µì…˜!
     properties:
       hibernate:
         format_sql: true
         default_batch_fetch_size: 1000

  # Redis ì„¤ì •
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug